print('prashant777'.isalnum())
print('prashantjha'.isalpha())
print('prashant3456789'.isalpha())
print('777f'.isdigit())
print('777d'.islower)
print('sdsdsd'.lower)
print(''.islower())
print('PRQASHANTj'.isupper())
print('My Name is Prashant'.istitle())
print(''.istitle)
print(''.isspace())
print("hello".startswith("he"))
print("hello".endswith("o"))
print("hrllo".format_map)
print("hrllo".count("a"))
print("prashant".index("r"))
print("prashant".count("a"))
print("prashant".find("b"))

